# Generated by Django 3.0.5 on 2020-06-01 13:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0017_player_player_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
